### ISSUE TITLE
Question about encoding/decoding of large numbers

### ISSUE THREAD

**Issue by fergiemcdowall** [dominictarr/charwise#14]
Thanks for giving the world this lib! Very useful for those of use who use sortable composite keys 🙂👍

It seems to work great with smaller numbers, but I get some strange behaviour with large numbers- is this a bug or a feature? If its a feature, what is the logic/algorithm? ->

```javascript
(async () => {
  const level = require('level')
  const charwise = require('charwise')
  
  const db = level('test', { keyEncoding: charwise })
  
  await db.put([ 'bar', 888888888888888888888 ], 'true')
  
  db.createReadStream().on('data', d => console.log(d))
  
  // Expected:    { key: [ 'bar', 888888888888888888888 ], value: 'true' }
  // Actual:      { key: [ 'bar', 888888888888888900000 ], value: 'true' }

})()
```

**Comment by fergiemcdowall** [comment]
In other words `888888888888888888888` gets converted to `888888888888888900000`, but why?

**Comment by PaulBlanche** [comment]
`888888888888888888888` is over `Number.MAX_SAFE_INTEGER` and cannot be repreeented safely as a number. This is neither a bug nor a feature, it is a limitation of javascript. 

You could use BigInt to have a safe representation of arbitrarily big numbers, but we don't have a codec to encode this type.

**Comment by fergiemcdowall** [comment]
OK- makes sense.
