### ISSUE TITLE
nested array bug

### ISSUE THREAD

**Issue by PaulBlanche** [dominictarr/charwise#2]
Nested array encoding/decoding flatten the array and insert empty strings :
```javascript
decode(encode(['a',['b'],'c'])) // returns ['a', '', 'b', 'c'] instead of ['a',['b'],'c']
```

**Comment by dominictarr** [comment]
Yes, this is in under TODO the redme: https://github.com/dominictarr/charwise#todo
I'm busy with other things currently, but would be very happy to merge a PR for this!
